### ISSUE TITLE
Failed to find ConsumerLibCommons.js from Instagram Server

### ISSUE THREAD

**Issue by datnewfix** [pishangujeniya/instagram-helper#89]
I see this script has been updated from the older one which had better directions. Im confused where exactly do I place my "Chat Thread ID" and the number of how many messages to skip in the script. Thx

**Comment by pishangujeniya** [comment]
You first try to follow the guidelines as mentioned in README, it will ask you in  prompt to enter the details.

**Comment by datnewfix** [comment]
I read the README section im still confused. On the last README it actually showed where to input the Chat Thread ID and the Skip number was already show.

**Comment by datnewfix** [comment]
![image](https://user-images.githubusercontent.com/130739518/231992178-2c735f56-d010-4b74-a96d-2dfba0bae932.png)

this is what im getting

**Comment by pishangujeniya** [comment]
@datnewfix you have not followed the readme properly. Please read the README properly. It has steps to follow the .vbs file and creating new chrome instance. Also you need to install an extension in the new instance of chrome which is mentioned in Readme.

**Comment by pishangujeniya** [comment]
@datnewfix I hope you have solved it.

Please close the issue.

**Comment by datnewfix** [comment]
The issue is not solved 
I dont know what im missing

**Comment by datnewfix** [comment]
![image](https://user-images.githubusercontent.com/130739518/232190322-f43608f6-3f50-4487-82ae-3303296a316b.png)

I follwed the directions in read me and get this still

**Comment by pishangujeniya** [comment]
@datnewfix  Answer me following questions

1. Are you using InstagramHelperChrome ?
2. Have you installed the [Disable Content-Security-Policy](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?hl=en) Extension in InstagramHelperChrome ?
3. Are you opening site using InstagramHelperChrome?

**Comment by datnewfix** [comment]
Yes 
![image](https://user-images.githubusercontent.com/130739518/232190435-cee7bfd5-82f4-4d33-99fc-b76f4a2f6b7c.png)

this correct right?

**Comment by datnewfix** [comment]
then i got to Instagram log in and hit F12 then I paste the script thats where im stuck

**Comment by pishangujeniya** [comment]
@datnewfix 
1. Open Instagram.com press the CSP icon, so that it becomes pink.
2. Try refreshing site, and it should be pink again automatically.
3. Now go to conversation, and run the script code in F12 console.

**Comment by datnewfix** [comment]
going to try now

**Comment by datnewfix** [comment]
I just did it .. when you say run the script you mean just paste it into the console like this right ? 
![image](https://user-images.githubusercontent.com/130739518/232190630-c77fda11-bfb0-4d55-b8e8-ddfba0714855.png)

How do i run it press enter?

**Comment by pishangujeniya** [comment]
@datnewfix  Yes, press Enter

**Comment by datnewfix** [comment]
I press enter and get this 
![image](https://user-images.githubusercontent.com/130739518/232190691-266c51b2-318e-4306-a64c-9b8c8da5a7fb.png)

**Comment by pishangujeniya** [comment]
@datnewfix  Thanks for reporting, its a bug.

Instagram servers have removed one of the script from there server - https://www.instagram.com/static/bundles/es6/ConsumerLibCommons.js/4f7f1faf9a94.js

Need to find the updated script from Instagram servers.

I am working on it.

**Comment by datnewfix** [comment]
ok thx!

**Comment by datnewfix** [comment]
I was using a different script about a month ago that was working fine.. this seems to be new

**Comment by pishangujeniya** [comment]
@datnewfix  That script which you were using, that will also not work now, as there has been some change done by Instagram developers, so we need to keep our script updated with it by reverse engineering it.

**Comment by datnewfix** [comment]
ok I understand! Ill wait patiently for update thx again

**Comment by pishangujeniya** [comment]
@datnewfix  Its fixed in the latest 3.1 version, you can use the latest code from the README.

**Comment by datnewfix** [comment]
doesnt seem to fix anything. looks like the same code unless im using the wrong one strange

**Comment by pishangujeniya** [comment]
@datnewfix It's fixed and added a flow guide with screenshots in README, you can follow it. 
You need to follow the steps very properly.

If it is still showing you an error, please attach the screenshot here.

**Comment by datnewfix** [comment]
I got it working thanks for all the help!

**Comment by datnewfix** [comment]
![image](https://user-images.githubusercontent.com/130739518/232258439-2395ddaa-a311-4794-9b1d-bbd56975828e.png)

its working for a little bit then this pops up ? anything I can do to stop this?

**Comment by pishangujeniya** [comment]
@datnewfix  Read the following

1. https://github.com/pishangujeniya/instagram-helper#-getting-too-often-try-again-tomorrow-error-or-429-response-code
2. https://github.com/pishangujeniya/instagram-helper/issues/6#issuecomment-663906500
